services:
  mysql:
    image: mysql:8.0
    container_name: sql_proxy_mysql
    environment:
      MYSQL_DATABASE: sql_proxy_demo
      MYSQL_USER: proxy_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "proxy_user", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10


  proxy:
    build: .
    container_name: sql_proxy
    depends_on:
      mysql:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - ./logs:/app/logs